### PR TITLE
[WIP] Allow model inheritance

### PR DESCRIPTION
**Pull request by Natureshadow**
Allow multi-inheritance in model.

### CODE REVIEW

**Comment by Natureshadow** [comment]
Work in progress, need to add tests.

**Comment by rroemhild** [comment]
Hmmm I merged your branch local, but something is wrong with the history :( Your PR is online in the master branch. Are you ok with this or should we try to merge this PR for history?

**Comment by Natureshadow** [comment]
@rroemhild I have no idea what the issue is… But yes, I'd really like to have this merged correctly ;).

I can have a look as well if you want.

**Comment by rroemhild** [comment]
Got it, the history is a bit fucked up. but that was my fault ;)

**Pull request merged**
