### PR TITLE
binding: allow for anonymous

### PR DESCRIPTION
**Pull request by cherusk**
Relevant e.g. for local binds,
where no security layer is of need at all.

Toggling TLS off via autobind is not lax enough.

### CODE REVIEW

**Comment by cherusk** [comment]
How swift are you at bringing out a fresh release based on that?

**Comment by rroemhild** [comment]
Thanks for your contribution. Had no time to look at your PR, but 100% CI test fail seems to be a problem :smile:

**Comment by cherusk** [comment]
Looks better, SIMPLE as default seems preferred.

**Comment by rroemhild** [comment]
Great! I'll release it as v0.9.0 this weekend.

**Pull request merged**
